framework:
    mailer:
        headers:
            from: 'Snowtricks <alprod81@gmail.com>'
            X-Custom-Header: 'foobar'
        envelope:
            sender: 'alprod81@gmail.com'
            recipients: ['alprod81@gmail.com']
        dsn: '%env(MAILER_DSN)%'
